# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
symbol = "Î»"     # The "symbol" segment is being set to "âœ"

[package]
disabled = false
symbol = "ğŸ "

[time]
disabled = false
format = "ğŸ•™[ %T ]"

[battery]
disabled = false
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[haskell]
symbol = "î· "

[git_branch]
symbol = "ğŸŒ± "

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = -1
symbol = "ğŸ’»mem "
style = "bold dimmed green"
